name: "CLA Check Workflow"

on:
  workflow_call:
    inputs:
      runs_on:
        type: string
        default: '["ubuntu-latest"]'
    secrets:
      CLA_ACTION_ACCESS_TOKEN:
        required: true

jobs:
  CLAAssistant:
    runs-on: ${{fromJSON(inputs.runs_on)}}
    steps:
      - name: "CLA Assistant"
        uses: contributor-assistant/github-action@v2.5.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.CLA_ACTION_ACCESS_TOKEN }}
        with:
          path-to-signatures: 'signatures/version1/cla.json'
          path-to-document: 'https://github.com/coreshop/coreshop/blob/4.0/CLA.md'
          branch: "main"
          allowlist: user1,bot*
          remote-organization-name: "coreshop"
          remote-repository-name: "cla"