name: "Documentation"

on:
  workflow_call:
    inputs:
      runs_on:
        type: string
        default: '["ubuntu-latest"]'

permissions:
  contents: read

jobs:
  docs:
    name: "CoreShop Docs Generator"
    runs-on: ${{ fromJSON(github.event.inputs.runs_on) }}
    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v4"

      - name: "Checkout Docs Generator"
        uses: "actions/checkout@v4"
        with:
          repository: "coreshop/docs-generator"
          ref: "main"
          path: "./docs-generator"

      - name: Prepare Docs
        working-directory: "./docs-generator"
        run: |
          rm -rf ./docs
          mv ../docs docs
          if [ ! -e "./docs/00_Introduction.md" ]; then
            cp -r ../README.md ./docs/
          fi
          
          rm docusaurus.config.js
          mv docusaurus.config.tests.js docusaurus.config.js

      - name: "Install Node"
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
          registry-url: 'https://registry.npmjs.org'

      - name: Build Docs
        working-directory: "./docs-generator"
        run: |
          npm install
          npm run build
